version: "3.7"
services:

  envoy:
    image: envoyproxy/envoy:v1.14.1
    volumes:
      - /etc/envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - xnet
    expose: ["8001", "443"]
    ports: ["80:80", "443:443"]

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.7
    volumes:
      - ./etcdata:/etcd-data
    networks:
      xnet:
        aliases:
          - etcd_cluster
    expose: ["2379", "2380"]
    ports: [ "2379:2379" ]
    command: /usr/local/bin/etcd --name s1 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://0.0.0.0:2380 --initial-cluster s1=http://0.0.0.0:2380 --initial-cluster-token tkn --initial-cluster-state new --log-level info --logger zap --log-outputs stderr

  xconf:
    image: onego/xconf:dev
    volumes:
      - ./web:/web
    networks:
      xnet:
        aliases:
          - xconfserver
    expose: 
      - "8900"
      - "8901"
    ports: 
      - "8900:8900"
      - "8901:8901"
    command: -l :8900 -s :8901 -dir /web -h etcd_cluster:2379

networks:
  xnet: {}
